# Generated by Django 5.2.11 on 2026-02-11 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='direccion_envio',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='orden',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_tienda', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orden',
            name='libro',
            field=models.ForeignKey(blank=True, help_text='Opcional cuando la orden se crea con el Builder (usuario + productos).', null=True, on_delete=django.db.models.deletion.CASCADE, to='tienda_app.libro'),
        ),
    ]
